### ISSUE TITLE
1.1.2 Interfaz Registro Usuario

### ISSUE THREAD

**Issue by gequintero4** [jumunara/JOSGA_proyect#10]
Creación de la interfaz de registro para los usuarios en android estudio.

**Comment by JOASTIAN98** [comment]
[https://drive.google.com/file/d/1NJLdqzdsXAYriR_GbPuVzuPaaOXf90p-/view?usp=sharing](url)

**Comment by JOASTIAN98** [comment]
https://drive.google.com/file/d/1NJLdqzdsXAYriR_GbPuVzuPaaOXf90p-/view?usp=sharing
